<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroServicioReportes.Aplicacion\MicroServicioReportes.Aplicacion.csproj" />
    <ProjectReference Include="..\MicroServicioReportes.Dominio\MicroServicioReportes.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CasiProgram\" />
    <Folder Include="Persistencia\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>

</Project>
