<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CasosDeUso\" />
    <Folder Include="DTOs\" />
    <Folder Include="Validadores\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroServicioProveedores.Dominio\MicroServicioProveedores.Dominio.csproj" />
  </ItemGroup>

</Project>
